# Generated by Django 4.2.13 on 2025-05-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_age_user_assets_user_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfinancialproduct',
            name='interest_rate_12m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
