# Generated by Django 5.2.1 on 2025-05-26 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_savedfinancialproduct_interest_rate_12m'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfinancialproduct',
            name='notify_on_rate_change',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=50)),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=20)),
                ('dcls_month', models.CharField(blank=True, max_length=6, null=True)),
                ('kor_co_nm', models.CharField(blank=True, max_length=100, null=True)),
                ('fin_prdt_nm', models.CharField(blank=True, max_length=255, null=True)),
                ('join_way', models.TextField(blank=True, null=True)),
                ('mtrt_int', models.TextField(blank=True, null=True)),
                ('spcl_cnd', models.TextField(blank=True, null=True)),
                ('join_deny', models.CharField(blank=True, max_length=50, null=True)),
                ('join_member', models.TextField(blank=True, null=True)),
                ('etc_note', models.TextField(blank=True, null=True)),
                ('max_limit', models.BigIntegerField(blank=True, null=True)),
                ('dcls_strt_day', models.DateField(blank=True, null=True)),
                ('dcls_end_day', models.DateField(blank=True, null=True)),
                ('fin_co_subm_day', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '금융 상품',
                'verbose_name_plural': '금융 상품들',
                'unique_together': {('fin_co_no', 'fin_prdt_cd', 'product_type')},
            },
        ),
        migrations.AddField(
            model_name='savedfinancialproduct',
            name='financial_product_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savers', to='accounts.financialproduct'),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(blank=True, max_length=1, null=True)),
                ('intr_rate_type_nm', models.CharField(blank=True, max_length=10, null=True)),
                ('save_trm', models.CharField(blank=True, max_length=3, null=True)),
                ('intr_rate', models.FloatField(blank=True, null=True)),
                ('intr_rate2', models.FloatField(blank=True, null=True)),
                ('financial_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='accounts.financialproduct')),
            ],
            options={
                'verbose_name': '상품 옵션 (금리)',
                'verbose_name_plural': '상품 옵션 (금리들)',
                'unique_together': {('financial_product', 'save_trm', 'intr_rate_type')},
            },
        ),
    ]
