# Generated by Django 5.2.1 on 2025-05-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_savedfinancialproduct_interest_rate_12m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='savings_tendency',
        ),
        migrations.AddField(
            model_name='user',
            name='investment_tendency',
            field=models.CharField(blank=True, choices=[('공격형', '공격형'), ('중립형', '중립형'), ('안정형', '안정형')], max_length=50, null=True),
        ),
    ]
