# Generated by Django 5.2.1 on 2025-05-27 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_savings_tendency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=512)),
                ('thumbnail_url', models.URLField(blank=True, max_length=512, null=True)),
                ('channel_title', models.CharField(blank=True, max_length=255, null=True)),
                ('published_at', models.CharField(blank=True, max_length=100, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'video_id')},
            },
        ),
    ]
