# Generated by Django 4.2.20 on 2025-04-20 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockdetail",
            name="user",
        ),
        migrations.AddField(
            model_name="stockdetail",
            name="chart",
            field=models.ImageField(blank=True, null=True, upload_to="stocks/charts/"),
        ),
        migrations.AddField(
            model_name="stockdetail",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_stocks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
