# Generated by Django 4.2.20 on 2025-04-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0002_remove_stockdetail_user_stockdetail_chart_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockdetail",
            name="market_capitalization",
        ),
    ]
