# Generated by Django 4.2.20 on 2025-04-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stocks", "0003_remove_stockdetail_market_capitalization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockdetail",
            name="name",
            field=models.TextField(unique=True),
        ),
    ]
